name: bloc_annotation_workspace

description: >-
  Monorepo for bloc_annotation and bloc_annotation_generator packages with examples.

environment:
    sdk: ^3.9.2

publish_to: none

workspace:
  - packages/bloc_annotation
  - packages/bloc_annotation_generator
  - examples/counter_cubit
  - examples/random_facts