name: counter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

resolution: workspace

# Add regular dependencies here.
dependencies:
  bloc_annotation: any
  bloc: ^9.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.10.0
  bloc_annotation_generator: any
