name: bloc_meta_generator
description: Code generator for bloc_meta package
version: 1.0.0
homepage: https://github.com/maranix/bloc_meta/tree/main/bloc_meta_generator
repository: https://github.com/maranix/bloc_meta
issue_tracker: https://github.com/maranix/bloc_meta/issues

topics:
  - bloc
  - cubit
  - codegen
  - flutter
  - dart

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^8.4.0
  bloc_meta: ^1.0.0
  build: ^4.0.2
  build_config: ^1.2.0
  code_builder: ^4.11.0
  dart_style: ^3.1.2
  source_gen: ^4.0.2

dev_dependencies:
  build_runner: ^2.10.0
  path: ^1.9.1
  pedantic_mono: ^1.35.0
  source_gen_test: ^1.3.2
  test: ^1.25.6
